version: '3.3'

services:
  userdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'userdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3305:3306'
    volumes:
      - userdb:/var/lib/mysql
  userservice:
    build: ./userservice
    ports:
      - '5001:5000'
    depends_on:
      - 'userdb'
    restart: always

  kweetdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'kweetdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - kweetdb:/var/lib/mysql
  kweetservice:
    build: ./kweetservice
    ports:
      - '5002:5000'
    depends_on:
      - 'kweetdb'
    restart: always

  gateway:
    build: ./gateway
    restart: always
  frontend:
    build: ./frontend
    ports:
      - '80:80'

volumes:
  userdb:
  kweetdb:
