version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  userdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3305:3306'
    volumes:
      - userdb:/var/lib/mysql
  userservice:
    build: ./userservice
    environment:
      PORT: 5000
      DB_NAME: 'db'
      DB_USER: 'root'
      DB_PASS: 'root'
      DB_HOST: 'userdb'
      DB_PORT: '3306'
    ports:
      - '5003:5000'
    depends_on:
      - 'userdb'
    volumes:
      - ./userservice:/usr/src/app
    restart: always

  kweetdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'kweetdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - kweetdb:/var/lib/mysql
  kweetservice:
    build: ./kweetservice
    ports:
      - '5002:5000'
    depends_on:
      - 'kweetdb'
    environment:
      PORT: 5000
      DB_NAME: 'db'
      DB_USER: 'root'
      DB_PASS: 'root'
      DB_HOST: 'kweetdb'
      DB_PORT: '3306'
    volumes:
      - ./kweetservice:/usr/src/app
    restart: always

  gateway:
    build: ./gateway
    ports:
      - '8080:8080'
      - '9876:9876'
    restart: always
  frontend:
    build: ./frontend
    ports:
      - '80:80'

volumes:
  userdb:
  kweetdb:
